<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>$(NoWarn);SYSLIB0014</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <InternalsVisibleTo Include="ServerBrowser.Tests" />
    <InternalsVisibleTo Include="ServerBrowser.Core" />
  </ItemGroup>
</Project>
