<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>SteamServerBrowser</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <Version>2.71.7</Version>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**/*.png" />
    <Content Include="Assets/App.png" TargetPath="SteamServerBrowser.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <ProjectReference Include="../ServerBrowser.Core/ServerBrowser.Core.csproj" />
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
  </ItemGroup>
</Project>
